import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const executor = readFileSync(new URL('../src/assistant/executor.ts', import.meta.url), 'utf8')
const prompts = readFileSync(new URL('../src/assistant/prompts.ts', import.meta.url), 'utf8')
const registry = readFileSync(new URL('../src/agent/registry.ts', import.meta.url), 'utf8')
const store = readFileSync(new URL('../src/assistant/store.ts', import.meta.url), 'utf8')
const skills = readFileSync(new URL('../src/assistant/skills.ts', import.meta.url), 'utf8')
const domainTools = readFileSync(new URL('../src/agent/domainTools.ts', import.meta.url), 'utf8')
const propertyIntake = readFileSync(new URL('../src/agent/propertyIntake.ts', import.meta.url), 'utf8')
const workspace = readFileSync(new URL('../src/database/workspace.ts', import.meta.url), 'utf8')

assert.match(skills, /export interface SkillAssessment/)
assert.match(skills, /shouldPlan = intent === 'execution'/)
assert.match(prompts, /getAgentFunctions\(_skill\?/) 
assert.match(prompts, /const toolFns: FunctionDef\[\] = TOOLS\s*\n?\s*\.filter\(/)
assert.match(prompts, /CORE_TOOLS = new Set\(\[/)
assert.match(registry, /export function validateToolArgs/)
assert.match(registry, /\[TOOL_INPUT_INVALID\]/)
assert.match(store, /const TASK_TRANSITIONS/)
assert.match(store, /status === 'completed' && \(!patch\.evidence/)
assert.match(executor, /transitionTaskRun\(runtimeTaskId, 'awaiting_user'/)
assert.match(executor, /getLatestTaskRun\(sessionId\)/)
assert.match(domainTools, /name: 'property_change_preview'/)
assert.match(domainTools, /name: 'attach_media_to_entity'/)
assert.match(propertyIntake, /mode: 'create'|mode: 'update'|mode: 'ambiguous'/)
assert.match(workspace, /export async function linkAttachmentToEntity/)
assert.match(workspace, /entity_media/)
console.log('Agent architecture invariants: PASS')
