import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const screen = readFileSync(new URL('../src/screens/assistant/AssistantScreen.tsx', import.meta.url), 'utf8')
const taskCard = readFileSync(new URL('../src/components/TaskCard.tsx', import.meta.url), 'utf8')
const store = readFileSync(new URL('../src/screens/assistant/agentChatStore.ts', import.meta.url), 'utf8')
const executor = readFileSync(new URL('../src/assistant/executor.ts', import.meta.url), 'utf8')
const llm = readFileSync(new URL('../src/assistant/llm.ts', import.meta.url), 'utf8')
const history = readFileSync(new URL('../src/assistant/history.ts', import.meta.url), 'utf8')
const appConfig = readFileSync(new URL('../app.json', import.meta.url), 'utf8')
const providers = readFileSync(new URL('../src/assistant/providers.ts', import.meta.url), 'utf8')

assert.match(screen, /kbHeight > 0 \? kbHeight \+ 4/)
assert.match(screen, /<TaskCard \/>/)
assert.match(taskCard, /const plan = useChatStore\(\(s\) => s\._plan\)/)
assert.match(store, /statusBar: \{ visible: boolean; phase: AgentPhase; thinking: boolean; steps: string\[\] \}/)
assert.match(store, /case 'thinking':/)
assert.match(store, /patch\.statusBar = \{ \.\.\.s\.statusBar, visible: true, thinking: true \}/)
assert.match(appConfig, /softwareKeyboardLayoutMode.*resize/)
assert.match(providers, /export function providerCapabilities/)
assert.match(executor, /const shouldPlan = assessment\.shouldPlan/)
assert.match(executor, /runtimePlan = shouldPlan \? planForSkill\(runtimeSkill, goal\) : null/)
assert.match(executor, /createTaskRun\(\{ sessionId, userRequest: goal, skillId: runtimeSkill\.id, intent: assessment\.intent/)
assert.match(executor, /if \(emitEvents && shouldPlan && runtimePlan\)/)
assert.match(llm, /export function normalizeToolCallId/)
assert.match(llm, /id: normalizeToolCallId\(call\.id \?\? raw\.id\)/)
assert.match(history, /normalizeToolCallId\(m\.meta\.tool_call_id\)/)
console.log('Assistant panel invariants: PASS')
