import assert from 'node:assert/strict'
import fs from 'node:fs'

const store = fs.readFileSync(new URL('../src/assistant/store.ts', import.meta.url), 'utf8')
const maps = fs.readFileSync(new URL('../src/screens/MapScreenV2/mapProviders.ts', import.meta.url), 'utf8')
const backup = fs.readFileSync(new URL('../src/database/backup.ts', import.meta.url), 'utf8')
const agentSettings = fs.readFileSync(new URL('../src/screens/assistant/AgentSettings.tsx', import.meta.url), 'utf8')

assert.match(store, /expo-secure-store/)
assert.match(store, /const SECRET_PREFIX/)
assert.match(store, /CREATE TABLE IF NOT EXISTS agent_secret_values/)
assert.match(store, /async function writeDatabaseSecret/)
assert.match(store, /export async function saveAgentApiKey/)
assert.match(store, /تعذر التحقق من حفظ مفتاح API داخل قاعدة البيانات المحلية/)
assert.match(store, /JSON\.stringify\(secretState\.keys\)/)
assert.match(store, /const keyMarkers = Object\.fromEntries\(Object\.keys\(keys \?\? \{\}\)\.map\(\(provider\) => \[provider, ''\]\)\)/)
assert.match(store, /return \{ keys: keyMarkers, customProviders: sanitizedCustom \}/)
assert.match(agentSettings, /onSaveApiKey/)
assert.match(agentSettings, /saveAgentApiKey\(activeKey, value\)/)
assert.match(agentSettings, /حفظ المفتاح في قاعدة البيانات/)
assert.doesNotMatch(agentSettings, /void save\(\{ keys:/)
assert.match(store, /const knownProviders = new Set\(\[/)
assert.match(store, /PROVIDERS\.filter\(\(provider\) => provider\.id !== 'custom'\)/)
assert.match(store, /const keyInputs = Object\.fromEntries/)
assert.match(maps, /MAP_SECRET_PREFIX/)
assert.match(maps, /JSON\.stringify\(fileState\)/)
assert.match(backup, /bodyHash/)
assert.match(backup, /includesKeys/)

console.log('Secret storage invariants: PASS')
